from enum import Enum

class DocumentType(str, Enum):
    BILL_OF_LADING = "BILL_OF_LADING"
    CUSTOMS_DECLARATION = "CUSTOMS_DECLARATION"
    COMMERCIAL_INVOICE = "COMMERCIAL_INVOICE"
    PACKING_LIST = "PACKING_LIST"
    CERTIFICATE_OF_ORIGIN = "CERTIFICATE_OF_ORIGIN"
    INSURANCE_CERTIFICATE = "INSURANCE_CERTIFICATE"
