"""Add kyc_documents table

Revision ID: 13e4f8c8fc37
Revises: 3247b739293f
Create Date: 2026-02-20 18:22:08.733222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13e4f8c8fc37'
down_revision: Union[str, None] = '3247b739293f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vehicle_type_enum = postgresql.ENUM(
        'SEDAN', 'SUV', 'HATCHBACK', 'VAN_MINIVAN', 'WAGON',
        'PICKUP', 'COUPE', 'CONVERTIBLE', 'BIKES', 'MACHINERY',
        name='vehicletype'
    )
    steering_enum = postgresql.ENUM('RIGHT_HAND', 'LEFT_HAND', name='steering')
    drive_enum = postgresql.ENUM('TWO_WD', 'FOUR_WD', 'AWD', name='drive')

    bind = op.get_bind()
    vehicle_type_enum.create(bind, checkfirst=True)
    steering_enum.create(bind, checkfirst=True)
    drive_enum.create(bind, checkfirst=True)

    op.alter_column('kyc_documents', 'nic_number',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='National Identity Card number (encrypted)',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Full name as per NIC',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'date_of_birth',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of birth from NIC',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Residential address (encrypted)',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Gender extracted from NIC (Male/Female)',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'nic_front_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supabase storage URL for NIC front image',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'nic_back_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supabase storage URL for NIC back image',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'selfie_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supabase storage URL for user selfie',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'extracted_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Raw JSON data extracted by Claude API from NIC images',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'discrepancies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Detected differences between extracted data and user-provided data',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='kycstatus'),
               postgresql_using='status::kycstatus',
               comment=None,
               existing_comment='Current KYC verification status',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'reviewed_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin user ID who reviewed this KYC',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when admin reviewed this KYC',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason for rejection if status is REJECTED',
               existing_nullable=True)
    op.drop_index('ix_users_is_kyc_verified', table_name='users')
    op.drop_column('users', 'is_kyc_verified')
    op.add_column('vehicles', sa.Column('stock_no', sa.String(length=100), nullable=False))
    op.add_column('vehicles', sa.Column('chassis', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('reg_year', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.Enum('SEDAN', 'SUV', 'HATCHBACK', 'VAN_MINIVAN', 'WAGON', 'PICKUP', 'COUPE', 'CONVERTIBLE', 'BIKES', 'MACHINERY', name='vehicletype'), nullable=True))
    op.add_column('vehicles', sa.Column('body_type', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('grade', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('engine_model', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('steering', sa.Enum('RIGHT_HAND', 'LEFT_HAND', name='steering'), nullable=True))
    op.add_column('vehicles', sa.Column('drive', sa.Enum('TWO_WD', 'FOUR_WD', 'AWD', name='drive'), nullable=True))
    op.add_column('vehicles', sa.Column('seats', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('doors', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('vehicles', sa.Column('dimensions', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('length_cm', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('width_cm', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('m3_size', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('vehicles', sa.Column('options', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('other_remarks', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_url', sa.Text(), nullable=True))
    op.add_column('vehicles', sa.Column('model_no', sa.String(length=100), nullable=True))
    op.alter_column('vehicles', 'price_jpy',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('vehicles', 'color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('vehicles', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_vehicles_auction_id', table_name='vehicles')
    op.create_index(op.f('ix_vehicles_stock_no'), 'vehicles', ['stock_no'], unique=True)
    op.drop_column('vehicles', 'auction_grade')
    op.drop_column('vehicles', 'auction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('auction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('auction_grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicles_stock_no'), table_name='vehicles')
    op.create_index('ix_vehicles_auction_id', 'vehicles', ['auction_id'], unique=True)
    op.alter_column('vehicles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('vehicles', 'color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('vehicles', 'price_jpy',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('vehicles', 'model_no')
    op.drop_column('vehicles', 'vehicle_url')
    op.drop_column('vehicles', 'other_remarks')
    op.drop_column('vehicles', 'options')
    op.drop_column('vehicles', 'm3_size')
    op.drop_column('vehicles', 'height_cm')
    op.drop_column('vehicles', 'width_cm')
    op.drop_column('vehicles', 'length_cm')
    op.drop_column('vehicles', 'dimensions')
    op.drop_column('vehicles', 'location')
    op.drop_column('vehicles', 'doors')
    op.drop_column('vehicles', 'seats')
    op.drop_column('vehicles', 'drive')
    op.drop_column('vehicles', 'steering')
    op.drop_column('vehicles', 'engine_model')
    op.drop_column('vehicles', 'grade')
    op.drop_column('vehicles', 'body_type')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'reg_year')
    op.drop_column('vehicles', 'chassis')
    op.drop_column('vehicles', 'stock_no')
    op.add_column('users', sa.Column('is_kyc_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, comment="Whether user's KYC is approved"))
    op.create_index('ix_users_is_kyc_verified', 'users', ['is_kyc_verified'], unique=False)
    op.alter_column('kyc_documents', 'rejection_reason',
               existing_type=sa.TEXT(),
               comment='Reason for rejection if status is REJECTED',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when admin reviewed this KYC',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'reviewed_by',
               existing_type=sa.UUID(),
               comment='Admin user ID who reviewed this KYC',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='kycstatus'),
               type_=sa.VARCHAR(length=8),
               postgresql_using='status::text',
               comment='Current KYC verification status',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'discrepancies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Detected differences between extracted data and user-provided data',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'extracted_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Raw JSON data extracted by Claude API from NIC images',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'selfie_url',
               existing_type=sa.TEXT(),
               comment='Supabase storage URL for user selfie',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'nic_back_url',
               existing_type=sa.TEXT(),
               comment='Supabase storage URL for NIC back image',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'nic_front_url',
               existing_type=sa.TEXT(),
               comment='Supabase storage URL for NIC front image',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='Gender extracted from NIC (Male/Female)',
               existing_nullable=True)
    op.alter_column('kyc_documents', 'address',
               existing_type=sa.TEXT(),
               comment='Residential address (encrypted)',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'date_of_birth',
               existing_type=sa.DATE(),
               comment='Date of birth from NIC',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full name as per NIC',
               existing_nullable=False)
    op.alter_column('kyc_documents', 'nic_number',
               existing_type=sa.VARCHAR(length=255),
               comment='National Identity Card number (encrypted)',
               existing_nullable=False)
    # ### end Alembic commands ###
