"""Add kyc_documents and file_integrity tables

Revision ID: 2b75160c0778
Revises: 64ab3d41d692
Create Date: 2026-02-23 08:46:30.077885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b75160c0778'
down_revision: Union[str, None] = '64ab3d41d692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_integrity', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_integrity', 'file_name')
    # ### end Alembic commands ###
