"""Add stock_no to vehicles

Revision ID: 3247b739293f
Revises: a7837696f581
Create Date: 2026-02-15 11:15:56.110836

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3247b739293f"
down_revision: Union[str, None] = "a7837696f581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vehicle_type_enum = postgresql.ENUM(
        "SEDAN",
        "SUV",
        "HATCHBACK",
        "VAN_MINIVAN",
        "WAGON",
        "PICKUP",
        "COUPE",
        "CONVERTIBLE",
        "BIKES",
        "MACHINERY",
        name="vehicletype",
    )
    steering_enum = postgresql.ENUM("RIGHT_HAND", "LEFT_HAND", name="steering")
    drive_enum = postgresql.ENUM("TWO_WD", "FOUR_WD", "AWD", name="drive")

    bind = op.get_bind()
    vehicle_type_enum.create(bind, checkfirst=True)
    steering_enum.create(bind, checkfirst=True)
    drive_enum.create(bind, checkfirst=True)

    op.alter_column(
        "kyc_documents",
        "extracted_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "kyc_documents",
        "discrepancies",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_idempotency",
        "response_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "security_events",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column("vehicles", sa.Column("stock_no", sa.String(length=100), nullable=False))
    op.add_column("vehicles", sa.Column("chassis", sa.String(length=100), nullable=True))
    op.add_column("vehicles", sa.Column("reg_year", sa.String(length=20), nullable=True))
    op.add_column("vehicles", sa.Column("vehicle_type", vehicle_type_enum, nullable=True))
    op.add_column("vehicles", sa.Column("body_type", sa.String(length=100), nullable=True))
    op.add_column("vehicles", sa.Column("grade", sa.String(length=100), nullable=True))
    op.add_column("vehicles", sa.Column("engine_model", sa.String(length=100), nullable=True))
    op.add_column("vehicles", sa.Column("steering", steering_enum, nullable=True))
    op.add_column("vehicles", sa.Column("drive", drive_enum, nullable=True))
    op.add_column("vehicles", sa.Column("seats", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("doors", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("location", sa.String(length=200), nullable=True))
    op.add_column("vehicles", sa.Column("dimensions", sa.Text(), nullable=True))
    op.add_column("vehicles", sa.Column("length_cm", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("width_cm", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("height_cm", sa.Integer(), nullable=True))
    op.add_column(
        "vehicles", sa.Column("m3_size", sa.DECIMAL(precision=10, scale=2), nullable=True)
    )
    op.add_column("vehicles", sa.Column("options", sa.Text(), nullable=True))
    op.add_column("vehicles", sa.Column("other_remarks", sa.Text(), nullable=True))
    op.add_column("vehicles", sa.Column("vehicle_url", sa.Text(), nullable=True))
    op.add_column("vehicles", sa.Column("model_no", sa.String(length=100), nullable=True))
    op.alter_column(
        "vehicles",
        "price_jpy",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicles",
        "color",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicles",
        "image_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vehicles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_vehicles_auction_id", table_name="vehicles")
    op.create_index(op.f("ix_vehicles_stock_no"), "vehicles", ["stock_no"], unique=True)
    op.drop_column("vehicles", "auction_grade")
    op.drop_column("vehicles", "auction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    vehicle_type_enum = postgresql.ENUM(
        "SEDAN",
        "SUV",
        "HATCHBACK",
        "VAN_MINIVAN",
        "WAGON",
        "PICKUP",
        "COUPE",
        "CONVERTIBLE",
        "BIKES",
        "MACHINERY",
        name="vehicletype",
    )
    steering_enum = postgresql.ENUM("RIGHT_HAND", "LEFT_HAND", name="steering")
    drive_enum = postgresql.ENUM("TWO_WD", "FOUR_WD", "AWD", name="drive")
    op.add_column(
        "vehicles",
        sa.Column("auction_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "vehicles",
        sa.Column("auction_grade", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_vehicles_stock_no"), table_name="vehicles")
    op.create_index("ix_vehicles_auction_id", "vehicles", ["auction_id"], unique=True)
    op.alter_column(
        "vehicles",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vehicles",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vehicles",
        "image_url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicles",
        "color",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicles",
        "price_jpy",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_column("vehicles", "model_no")
    op.drop_column("vehicles", "vehicle_url")
    op.drop_column("vehicles", "other_remarks")
    op.drop_column("vehicles", "options")
    op.drop_column("vehicles", "m3_size")
    op.drop_column("vehicles", "height_cm")
    op.drop_column("vehicles", "width_cm")
    op.drop_column("vehicles", "length_cm")
    op.drop_column("vehicles", "dimensions")
    op.drop_column("vehicles", "location")
    op.drop_column("vehicles", "doors")
    op.drop_column("vehicles", "seats")
    op.drop_column("vehicles", "drive")
    op.drop_column("vehicles", "steering")
    op.drop_column("vehicles", "engine_model")
    op.drop_column("vehicles", "grade")
    op.drop_column("vehicles", "body_type")
    op.drop_column("vehicles", "vehicle_type")
    op.drop_column("vehicles", "reg_year")
    op.drop_column("vehicles", "chassis")
    op.drop_column("vehicles", "stock_no")
    drive_enum.drop(bind, checkfirst=True)
    steering_enum.drop(bind, checkfirst=True)
    vehicle_type_enum.drop(bind, checkfirst=True)
    op.alter_column(
        "security_events",
        "details",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_idempotency",
        "response_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "kyc_documents",
        "discrepancies",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "kyc_documents",
        "extracted_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
