"""Add order status history table (CD-180)

Revision ID: 49cb44740c5d
Revises: e4c1a2b3d4f5
Create Date: 2026-03-08 18:24:48.599219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49cb44740c5d'
down_revision: Union[str, None] = 'e4c1a2b3d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('gazettes', 'raw_extracted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('order_status_history', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('order_status_history', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.create_index('idx_order_status_history_created_at', 'order_status_history', ['created_at'], unique=False)
    op.create_index('idx_order_status_history_to_status', 'order_status_history', ['to_status'], unique=False)
    op.drop_index('idx_payments_created_at', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_user_id', table_name='payments')
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('shipment_details', sa.Column('vessel_registration', sa.String(length=100), nullable=True))
    op.add_column('shipment_details', sa.Column('estimated_departure_date', sa.Date(), nullable=True))
    op.add_column('shipment_details', sa.Column('actual_departure_date', sa.Date(), nullable=True))
    op.add_column('shipment_details', sa.Column('bill_of_landing_number', sa.String(length=100), nullable=True))
    op.add_column('shipment_details', sa.Column('documents_uploaded', sa.Boolean(), nullable=False))
    op.add_column('shipment_details', sa.Column('approved', sa.Boolean(), nullable=False))
    op.alter_column('vehicles', 'fuel_type',
               existing_type=postgresql.ENUM('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'CNG', name='fueltype'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('vehicles', 'transmission',
               existing_type=postgresql.ENUM('MANUAL', 'AUTOMATIC', 'CVT', 'SEMI_AUTOMATIC', name='transmission'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'transmission',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MANUAL', 'AUTOMATIC', 'CVT', 'SEMI_AUTOMATIC', name='transmission'),
               existing_nullable=True)
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'CNG', name='fueltype'),
               existing_nullable=True)
    op.drop_column('shipment_details', 'approved')
    op.drop_column('shipment_details', 'documents_uploaded')
    op.drop_column('shipment_details', 'bill_of_landing_number')
    op.drop_column('shipment_details', 'actual_departure_date')
    op.drop_column('shipment_details', 'estimated_departure_date')
    op.drop_column('shipment_details', 'vessel_registration')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.create_index('idx_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_created_at', 'payments', ['created_at'], unique=False)
    op.drop_index('idx_order_status_history_to_status', table_name='order_status_history')
    op.drop_index('idx_order_status_history_created_at', table_name='order_status_history')
    op.drop_column('order_status_history', 'user_agent')
    op.drop_column('order_status_history', 'ip_address')
    op.alter_column('gazettes', 'raw_extracted',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
