"""Add KYC security columns

Revision ID: 5c21fce81567
Revises: a7837696f581
Create Date: 2026-01-29 18:10:01.750251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c21fce81567'
down_revision: Union[str, None] = 'a7837696f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_documents', sa.Column('nic_front_hash', sa.String(length=64), nullable=True))
    op.add_column('kyc_documents', sa.Column('nic_back_hash', sa.String(length=64), nullable=True))
    op.add_column('kyc_documents', sa.Column('selfie_hash', sa.String(length=64), nullable=True))
    op.alter_column('kyc_documents', 'nic_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('kyc_documents', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('kyc_documents', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('kyc_documents', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('kyc_documents', 'nic_front_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('kyc_documents', 'nic_back_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('kyc_documents', 'selfie_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc_documents', 'selfie_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('kyc_documents', 'nic_back_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('kyc_documents', 'nic_front_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('kyc_documents', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('kyc_documents', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('kyc_documents', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('kyc_documents', 'nic_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('kyc_documents', 'selfie_hash')
    op.drop_column('kyc_documents', 'nic_back_hash')
    op.drop_column('kyc_documents', 'nic_front_hash')
    # ### end Alembic commands ###
