"""Initial database schema

Revision ID: a7837696f581
Revises: 
Create Date: 2026-01-27 04:03:44.333880

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a7837696f581"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_idempotency",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_idempotency_idempotency_key"),
        "payment_idempotency",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("google_id", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "CUSTOMER",
                "ADMIN",
                "CLEARING_AGENT",
                "FINANCE_PARTNER",
                "EXPORTER",
                name="role",
            ),
            nullable=False,
        ),
        sa.Column("failed_auth_attempts", sa.Integer(), nullable=False),
        sa.Column("last_failed_auth", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("auction_id", sa.String(length=100), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("price_jpy", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("engine_cc", sa.Integer(), nullable=True),
        sa.Column(
            "fuel_type",
            sa.Enum("PETROL", "DIESEL", "HYBRID", "ELECTRIC", "CNG", name="fueltype"),
            nullable=True,
        ),
        sa.Column(
            "transmission",
            sa.Enum("MANUAL", "AUTOMATIC", "CVT", "SEMI_AUTOMATIC", name="transmission"),
            nullable=True,
        ),
        sa.Column("auction_grade", sa.String(length=10), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "RESERVED", "SOLD", "UNAVAILABLE", name="vehiclestatus"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_auction_id"), "vehicles", ["auction_id"], unique=True)
    op.create_index(op.f("ix_vehicles_make"), "vehicles", ["make"], unique=False)
    op.create_index(op.f("ix_vehicles_model"), "vehicles", ["model"], unique=False)
    op.create_index(op.f("ix_vehicles_status"), "vehicles", ["status"], unique=False)
    op.create_index(op.f("ix_vehicles_year"), "vehicles", ["year"], unique=False)
    op.create_table(
        "file_integrity",
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("last_verified", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "FAILED", "TAMPERED", name="verificationstatus"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_integrity_file_url"), "file_integrity", ["file_url"], unique=True)
    op.create_index(
        op.f("ix_file_integrity_sha256_hash"),
        "file_integrity",
        ["sha256_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_integrity_verification_status"),
        "file_integrity",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "gdpr_requests",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("DATA_EXPORT", "DATA_DELETION", "DATA_RECTIFICATION", name="requesttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="requeststatus"),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("export_file_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gdpr_requests_status"), "gdpr_requests", ["status"], unique=False)
    op.create_index(op.f("ix_gdpr_requests_user_id"), "gdpr_requests", ["user_id"], unique=False)
    op.create_table(
        "kyc_documents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nic_number", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("nic_front_url", sa.Text(), nullable=False),
        sa.Column("nic_back_url", sa.Text(), nullable=False),
        sa.Column("selfie_url", sa.Text(), nullable=False),
        sa.Column("extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("discrepancies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="kycstatus"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kyc_documents_status"), "kyc_documents", ["status"], unique=False)
    op.create_index(op.f("ix_kyc_documents_user_id"), "kyc_documents", ["user_id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PAYMENT_CONFIRMED",
                "LC_REQUESTED",
                "LC_APPROVED",
                "LC_REJECTED",
                "ASSIGNED_TO_EXPORTER",
                "SHIPMENT_DOCS_UPLOADED",
                "AWAITING_SHIPMENT_CONFIRMATION",
                "SHIPPED",
                "IN_TRANSIT",
                "ARRIVED_AT_PORT",
                "CUSTOMS_CLEARANCE",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("shipping_address", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("total_cost_lkr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index(op.f("ix_orders_vehicle_id"), "orders", ["vehicle_id"], unique=False)
    op.create_table(
        "rate_limit_violations",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("limit_tier", sa.String(length=20), nullable=True),
        sa.Column("requests_attempted", sa.Integer(), nullable=True),
        sa.Column("limit_exceeded", sa.Integer(), nullable=True),
        sa.Column(
            "violation_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rate_limit_violations_ip_address"),
        "rate_limit_violations",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_violations_user_id"),
        "rate_limit_violations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_limit_violations_violation_time"),
        "rate_limit_violations",
        ["violation_time"],
        unique=False,
    )
    op.create_table(
        "security_events",
        sa.Column(
            "event_type",
            sa.Enum(
                "AUTH_FAILURE",
                "TOKEN_REUSE",
                "SUSPICIOUS_ACTIVITY",
                "IMPOSSIBLE_TRAVEL",
                "RATE_LIMIT_EXCEEDED",
                "PAYMENT_MANIPULATION",
                "FILE_TAMPERING",
                "UNAUTHORIZED_ACCESS",
                "ACCOUNT_LOCKOUT",
                name="securityeventtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_events_event_type"),
        "security_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_events_severity"),
        "security_events",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_events_user_id"), "security_events", ["user_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_active",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_reputation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("trust_score", sa.Integer(), nullable=False),
        sa.Column("successful_orders", sa.Integer(), nullable=False),
        sa.Column("failed_payments", sa.Integer(), nullable=False),
        sa.Column("kyc_rejections", sa.Integer(), nullable=False),
        sa.Column("security_alerts", sa.Integer(), nullable=False),
        sa.Column(
            "current_tier",
            sa.Enum("SUSPICIOUS", "STANDARD", "TRUSTED", "PREMIUM", name="usertier"),
            nullable=False,
        ),
        sa.Column("impossible_travel_detected", sa.Boolean(), nullable=False),
        sa.Column("multiple_devices_flagged", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_reputation_current_tier"),
        "user_reputation",
        ["current_tier"],
        unique=False,
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "CREATED",
                "PAYMENT_CONFIRMED",
                "LC_REQUESTED",
                "LC_APPROVED",
                "LC_REJECTED",
                "ASSIGNED_TO_EXPORTER",
                "SHIPMENT_DOCS_UPLOADED",
                "AWAITING_SHIPMENT_CONFIRMATION",
                "SHIPPED",
                "IN_TRANSIT",
                "ARRIVED_AT_PORT",
                "CUSTOMS_CLEARANCE",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "CREATED",
                "PAYMENT_CONFIRMED",
                "LC_REQUESTED",
                "LC_APPROVED",
                "LC_REJECTED",
                "ASSIGNED_TO_EXPORTER",
                "SHIPMENT_DOCS_UPLOADED",
                "AWAITING_SHIPMENT_CONFIRMATION",
                "SHIPPED",
                "IN_TRANSIT",
                "ARRIVED_AT_PORT",
                "CUSTOMS_CLEARANCE",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"),
        "order_status_history",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("payhere_payment_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_one_completed_payment_per_order",
        "payments",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status = 'COMPLETED'"),
    )
    op.create_index(
        op.f("ix_payments_idempotency_key"),
        "payments",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_payments_payhere_payment_id"),
        "payments",
        ["payhere_payment_id"],
        unique=True,
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "shipment_details",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("exporter_id", sa.UUID(), nullable=False),
        sa.Column("vessel_name", sa.String(length=255), nullable=True),
        sa.Column("voyage_number", sa.String(length=100), nullable=True),
        sa.Column("departure_port", sa.String(length=255), nullable=True),
        sa.Column("arrival_port", sa.String(length=255), nullable=True),
        sa.Column("departure_date", sa.Date(), nullable=True),
        sa.Column("estimated_arrival_date", sa.Date(), nullable=True),
        sa.Column("actual_arrival_date", sa.Date(), nullable=True),
        sa.Column("container_number", sa.String(length=100), nullable=True),
        sa.Column("seal_number", sa.String(length=100), nullable=True),
        sa.Column("tracking_number", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_SHIPMENT",
                "DOCS_UPLOADED",
                "AWAITING_ADMIN_APPROVAL",
                "CONFIRMED_SHIPPED",
                name="shipmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_approved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipment_details_exporter_id"),
        "shipment_details",
        ["exporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipment_details_order_id"),
        "shipment_details",
        ["order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_shipment_details_status"), "shipment_details", ["status"], unique=False
    )
    op.create_table(
        "shipping_documents",
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "BILL_OF_LADING",
                "PACKING_LIST",
                "EXPORT_CERTIFICATE",
                "COMMERCIAL_INVOICE",
                "INSURANCE_CERTIFICATE",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipment_details.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipping_documents_document_type"),
        "shipping_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shipping_documents_shipment_id"),
        "shipping_documents",
        ["shipment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shipping_documents_shipment_id"), table_name="shipping_documents")
    op.drop_index(op.f("ix_shipping_documents_document_type"), table_name="shipping_documents")
    op.drop_table("shipping_documents")
    op.drop_index(op.f("ix_shipment_details_status"), table_name="shipment_details")
    op.drop_index(op.f("ix_shipment_details_order_id"), table_name="shipment_details")
    op.drop_index(op.f("ix_shipment_details_exporter_id"), table_name="shipment_details")
    op.drop_table("shipment_details")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_payhere_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_idempotency_key"), table_name="payments")
    op.drop_index(
        "idx_one_completed_payment_per_order",
        table_name="payments",
        postgresql_where=sa.text("status = 'COMPLETED'"),
    )
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_user_reputation_current_tier"), table_name="user_reputation")
    op.drop_table("user_reputation")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_security_events_user_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_severity"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_event_type"), table_name="security_events")
    op.drop_table("security_events")
    op.drop_index(
        op.f("ix_rate_limit_violations_violation_time"),
        table_name="rate_limit_violations",
    )
    op.drop_index(op.f("ix_rate_limit_violations_user_id"), table_name="rate_limit_violations")
    op.drop_index(op.f("ix_rate_limit_violations_ip_address"), table_name="rate_limit_violations")
    op.drop_table("rate_limit_violations")
    op.drop_index(op.f("ix_orders_vehicle_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_kyc_documents_user_id"), table_name="kyc_documents")
    op.drop_index(op.f("ix_kyc_documents_status"), table_name="kyc_documents")
    op.drop_table("kyc_documents")
    op.drop_index(op.f("ix_gdpr_requests_user_id"), table_name="gdpr_requests")
    op.drop_index(op.f("ix_gdpr_requests_status"), table_name="gdpr_requests")
    op.drop_table("gdpr_requests")
    op.drop_index(op.f("ix_file_integrity_verification_status"), table_name="file_integrity")
    op.drop_index(op.f("ix_file_integrity_sha256_hash"), table_name="file_integrity")
    op.drop_index(op.f("ix_file_integrity_file_url"), table_name="file_integrity")
    op.drop_table("file_integrity")
    op.drop_index(op.f("ix_vehicles_year"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_status"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_model"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_make"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_auction_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_payment_idempotency_idempotency_key"), table_name="payment_idempotency")
    op.drop_table("payment_idempotency")
    # ### end Alembic commands ###
