"""Add orders and order_status_history tables

Revision ID: cb635df9f614
Revises: a7837696f581
Create Date: 2026-02-10 07:12:02.138887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb635df9f614'
down_revision: Union[str, None] = 'a7837696f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kyc_documents_status', table_name='kyc_documents')
    op.drop_index('ix_kyc_documents_user_id', table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index('idx_one_completed_payment_per_order', table_name='payments', postgresql_where="(status = 'COMPLETED'::paymentstatus)")
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index('ix_payments_payhere_payment_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_google_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_payment_idempotency_idempotency_key', table_name='payment_idempotency')
    op.drop_table('payment_idempotency')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_vehicle_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_file_integrity_file_url', table_name='file_integrity')
    op.drop_index('ix_file_integrity_sha256_hash', table_name='file_integrity')
    op.drop_index('ix_file_integrity_verification_status', table_name='file_integrity')
    op.drop_table('file_integrity')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_order_status_history_order_id', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('ix_gdpr_requests_status', table_name='gdpr_requests')
    op.drop_index('ix_gdpr_requests_user_id', table_name='gdpr_requests')
    op.drop_table('gdpr_requests')
    op.drop_index('ix_rate_limit_violations_ip_address', table_name='rate_limit_violations')
    op.drop_index('ix_rate_limit_violations_user_id', table_name='rate_limit_violations')
    op.drop_index('ix_rate_limit_violations_violation_time', table_name='rate_limit_violations')
    op.drop_table('rate_limit_violations')
    op.drop_index('ix_vehicles_auction_id', table_name='vehicles')
    op.drop_index('ix_vehicles_make', table_name='vehicles')
    op.drop_index('ix_vehicles_model', table_name='vehicles')
    op.drop_index('ix_vehicles_status', table_name='vehicles')
    op.drop_index('ix_vehicles_year', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_security_events_event_type', table_name='security_events')
    op.drop_index('ix_security_events_severity', table_name='security_events')
    op.drop_index('ix_security_events_user_id', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_shipment_details_exporter_id', table_name='shipment_details')
    op.drop_index('ix_shipment_details_order_id', table_name='shipment_details')
    op.drop_index('ix_shipment_details_status', table_name='shipment_details')
    op.drop_table('shipment_details')
    op.drop_index('ix_shipping_documents_document_type', table_name='shipping_documents')
    op.drop_index('ix_shipping_documents_shipment_id', table_name='shipping_documents')
    op.drop_table('shipping_documents')
    op.drop_index('ix_user_reputation_current_tier', table_name='user_reputation')
    op.drop_table('user_reputation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reputation',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trust_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_orders', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_payments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kyc_rejections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('security_alerts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_tier', postgresql.ENUM('SUSPICIOUS', 'STANDARD', 'TRUSTED', 'PREMIUM', name='usertier'), autoincrement=False, nullable=False),
    sa.Column('impossible_travel_detected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('multiple_devices_flagged', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_reputation_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_reputation_pkey')
    )
    op.create_index('ix_user_reputation_current_tier', 'user_reputation', ['current_tier'], unique=False)
    op.create_table('shipping_documents',
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('BILL_OF_LADING', 'PACKING_LIST', 'EXPORT_CERTIFICATE', 'COMMERCIAL_INVOICE', 'INSURANCE_CERTIFICATE', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_details.id'], name='shipping_documents_shipment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='shipping_documents_uploaded_by_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='shipping_documents_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipping_documents_pkey')
    )
    op.create_index('ix_shipping_documents_shipment_id', 'shipping_documents', ['shipment_id'], unique=False)
    op.create_index('ix_shipping_documents_document_type', 'shipping_documents', ['document_type'], unique=False)
    op.create_table('shipment_details',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exporter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vessel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('voyage_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('departure_port', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('arrival_port', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estimated_arrival_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_arrival_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('container_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seal_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_SHIPMENT', 'DOCS_UPLOADED', 'AWAITING_ADMIN_APPROVAL', 'CONFIRMED_SHIPPED', name='shipmentstatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('admin_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('admin_approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_approved_by'], ['users.id'], name='shipment_details_admin_approved_by_fkey'),
    sa.ForeignKeyConstraint(['exporter_id'], ['users.id'], name='shipment_details_exporter_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='shipment_details_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shipment_details_pkey')
    )
    op.create_index('ix_shipment_details_status', 'shipment_details', ['status'], unique=False)
    op.create_index('ix_shipment_details_order_id', 'shipment_details', ['order_id'], unique=True)
    op.create_index('ix_shipment_details_exporter_id', 'shipment_details', ['exporter_id'], unique=False)
    op.create_table('security_events',
    sa.Column('event_type', postgresql.ENUM('AUTH_FAILURE', 'TOKEN_REUSE', 'SUSPICIOUS_ACTIVITY', 'IMPOSSIBLE_TRAVEL', 'RATE_LIMIT_EXCEEDED', 'PAYMENT_MANIPULATION', 'FILE_TAMPERING', 'UNAUTHORIZED_ACCESS', 'ACCOUNT_LOCKOUT', name='securityeventtype'), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name='security_events_resolved_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='security_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='security_events_pkey')
    )
    op.create_index('ix_security_events_user_id', 'security_events', ['user_id'], unique=False)
    op.create_index('ix_security_events_severity', 'security_events', ['severity'], unique=False)
    op.create_index('ix_security_events_event_type', 'security_events', ['event_type'], unique=False)
    op.create_table('vehicles',
    sa.Column('auction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_jpy', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('mileage_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine_cc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', postgresql.ENUM('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'CNG', name='fueltype'), autoincrement=False, nullable=True),
    sa.Column('transmission', postgresql.ENUM('MANUAL', 'AUTOMATIC', 'CVT', 'SEMI_AUTOMATIC', name='transmission'), autoincrement=False, nullable=True),
    sa.Column('auction_grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'RESERVED', 'SOLD', 'UNAVAILABLE', name='vehiclestatus'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vehicles_year', 'vehicles', ['year'], unique=False)
    op.create_index('ix_vehicles_status', 'vehicles', ['status'], unique=False)
    op.create_index('ix_vehicles_model', 'vehicles', ['model'], unique=False)
    op.create_index('ix_vehicles_make', 'vehicles', ['make'], unique=False)
    op.create_index('ix_vehicles_auction_id', 'vehicles', ['auction_id'], unique=True)
    op.create_table('rate_limit_violations',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('limit_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requests_attempted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit_exceeded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('violation_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rate_limit_violations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rate_limit_violations_pkey')
    )
    op.create_index('ix_rate_limit_violations_violation_time', 'rate_limit_violations', ['violation_time'], unique=False)
    op.create_index('ix_rate_limit_violations_user_id', 'rate_limit_violations', ['user_id'], unique=False)
    op.create_index('ix_rate_limit_violations_ip_address', 'rate_limit_violations', ['ip_address'], unique=False)
    op.create_table('gdpr_requests',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('DATA_EXPORT', 'DATA_DELETION', 'DATA_RECTIFICATION', name='requesttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('export_file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gdpr_requests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='gdpr_requests_pkey')
    )
    op.create_index('ix_gdpr_requests_user_id', 'gdpr_requests', ['user_id'], unique=False)
    op.create_index('ix_gdpr_requests_status', 'gdpr_requests', ['status'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_status', postgresql.ENUM('CREATED', 'PAYMENT_CONFIRMED', 'LC_REQUESTED', 'LC_APPROVED', 'LC_REJECTED', 'ASSIGNED_TO_EXPORTER', 'SHIPMENT_DOCS_UPLOADED', 'AWAITING_SHIPMENT_CONFIRMATION', 'SHIPPED', 'IN_TRANSIT', 'ARRIVED_AT_PORT', 'CUSTOMS_CLEARANCE', 'DELIVERED', 'CANCELLED', name='orderstatus'), autoincrement=False, nullable=True),
    sa.Column('to_status', postgresql.ENUM('CREATED', 'PAYMENT_CONFIRMED', 'LC_REQUESTED', 'LC_APPROVED', 'LC_REJECTED', 'ASSIGNED_TO_EXPORTER', 'SHIPMENT_DOCS_UPLOADED', 'AWAITING_SHIPMENT_CONFIRMATION', 'SHIPPED', 'IN_TRANSIT', 'ARRIVED_AT_PORT', 'CUSTOMS_CLEARANCE', 'DELIVERED', 'CANCELLED', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='order_status_history_changed_by_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_status_history_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_status_history_pkey')
    )
    op.create_index('ix_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('file_integrity',
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sha256_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_status', postgresql.ENUM('PENDING', 'VERIFIED', 'FAILED', 'TAMPERED', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='file_integrity_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_integrity_pkey')
    )
    op.create_index('ix_file_integrity_verification_status', 'file_integrity', ['verification_status'], unique=False)
    op.create_index('ix_file_integrity_sha256_hash', 'file_integrity', ['sha256_hash'], unique=False)
    op.create_index('ix_file_integrity_file_url', 'file_integrity', ['file_url'], unique=True)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'PAYMENT_CONFIRMED', 'LC_REQUESTED', 'LC_APPROVED', 'LC_REJECTED', 'ASSIGNED_TO_EXPORTER', 'SHIPMENT_DOCS_UPLOADED', 'AWAITING_SHIPMENT_CONFIRMATION', 'SHIPPED', 'IN_TRANSIT', 'ARRIVED_AT_PORT', 'CUSTOMS_CLEARANCE', 'DELIVERED', 'CANCELLED', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False),
    sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_cost_lkr', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='orders_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_orders_vehicle_id', 'orders', ['vehicle_id'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('payment_idempotency',
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_idempotency_pkey')
    )
    op.create_index('ix_payment_idempotency_idempotency_key', 'payment_idempotency', ['idempotency_key'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('CUSTOMER', 'ADMIN', 'CLEARING_AGENT', 'FINANCE_PARTNER', 'EXPORTER', name='role'), autoincrement=False, nullable=False),
    sa.Column('failed_auth_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_failed_auth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payhere_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_payhere_payment_id', 'payments', ['payhere_payment_id'], unique=True)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=True)
    op.create_index('idx_one_completed_payment_per_order', 'payments', ['order_id'], unique=True, postgresql_where="(status = 'COMPLETED'::paymentstatus)")
    op.create_table('kyc_documents',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nic_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nic_front_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nic_back_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('selfie_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discrepancies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='kycstatus'), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='kyc_documents_reviewed_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kyc_documents_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kyc_documents_pkey')
    )
    op.create_index('ix_kyc_documents_user_id', 'kyc_documents', ['user_id'], unique=True)
    op.create_index('ix_kyc_documents_status', 'kyc_documents', ['status'], unique=False)
    # ### end Alembic commands ###
